"""
Orchestrator — the conversation state machine.

  Caller  <---WebSocket--->  Orchestrator  <---WebSocket--->  STT Service
                                    |
                                    +---WebSocket---> NLU/LLM Service (HTTP)
                                    +---WebSocket---> TTS Service

- Caller connects to  ws://<host>:8001/ws/call?token=...
- Caller sends raw audio bytes (same format the STT Service expects)
- Orchestrator forwards that audio to the STT Service (as a client of it —
  same role your test_mic_stream.py script has been playing)
- On each transcript event, the Orchestrator advances its call state machine,
  calls the NLU/LLM Service for a real reply, and streams that reply through
  the sentence chunker into the TTS Service - so the caller hears the first
  sentence while later ones are still being generated by the LLM.

Run with:
    uvicorn orchestrator_service:app --reload --port 8001

Needs the STT, NLU, and TTS Services already running (ports 8000/8002/8003).
"""

import asyncio
import json
import logging
import os
import uuid
from contextlib import asynccontextmanager

import httpx
import websockets
from dotenv import load_dotenv
from fastapi import FastAPI, WebSocket, WebSocketDisconnect
from websockets.exceptions import ConnectionClosed

from call_state import CallSession, CallState
from sentence_chunker import SentenceChunker

load_dotenv()
logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
logger = logging.getLogger("orchestrator")

# One shared HTTP client for the whole process, instead of opening a new
# connection on every single turn. On localhost this saves relatively
# little, but it's the correct pattern regardless of where the NLU Service
# ends up running later, and costs nothing to do now.
http_client: httpx.AsyncClient | None = None


@asynccontextmanager
async def lifespan(app: FastAPI):
    global http_client
    http_client = httpx.AsyncClient(timeout=30.0)
    yield
    await http_client.aclose()


app = FastAPI(title="Orchestrator", lifespan=lifespan)

STT_SERVICE_URL = os.environ.get("STT_SERVICE_URL", "ws://localhost:8000/ws/transcribe")
STT_SERVICE_TOKEN = os.environ.get("STT_SERVICE_TOKEN", "")

NLU_SERVICE_URL = os.environ.get("NLU_SERVICE_URL", "http://localhost:8002/reply/stream")
NLU_SERVICE_TOKEN = os.environ.get("NLU_SERVICE_TOKEN", "")

TTS_SERVICE_URL = os.environ.get("TTS_SERVICE_URL", "ws://localhost:8003/ws/synthesize")
TTS_SERVICE_TOKEN = os.environ.get("TTS_SERVICE_TOKEN", "")

ORCHESTRATOR_TOKEN = os.environ.get("ORCHESTRATOR_TOKEN")
if not ORCHESTRATOR_TOKEN:
    logger.warning(
        "ORCHESTRATOR_TOKEN is not set — /ws/call is UNAUTHENTICATED. "
        "Fine for local testing, not for anything public."
    )


async def speak_text(tts_ws, client_ws, text: str):
    """
    Sends one complete sentence to the (already open, persistent) TTS
    Service connection and relays the resulting audio straight to the
    caller as it's generated. This is what actually lets the bot start
    speaking sentence 1 while the LLM is still generating sentence 2 -
    each sentence is synthesized and relayed as soon as it's ready, not
    after the whole reply is complete.

    Note: this call is awaited sequentially per sentence, so synthesis of
    sentence 2 doesn't begin until sentence 1's audio has been fully
    relayed. That's a reasonable v1 - most of the perceived speed benefit
    already comes from not waiting for the FULL reply before speaking
    anything. True pipelining (synthesizing sentence 2 while sentence 1 is
    still playing) would need a queue between NLU consumption and TTS
    calls - a fine future refinement, not required for this to feel fast.

    Failures here are logged and swallowed, not raised - losing the audio
    for one sentence shouldn't end the whole call.
    """
    try:
        await tts_ws.send(text)
        while True:
            message = await tts_ws.recv()
            if isinstance(message, bytes):
                await client_ws.send_bytes(message)
            else:
                data = json.loads(message)
                if data.get("event") == "utterance_end":
                    break
                if "error" in data:
                    logger.error("TTS Service reported an error: %s", data.get("detail"))
                    break
    except Exception as e:
        logger.exception("TTS Service call failed: %s", e)


async def stream_nlu_reply(conversation_history: list[dict]):
    """
    Calls the NLU/LLM Service's streaming endpoint and yields text deltas as
    they arrive - this is what lets the Orchestrator react to the first few
    words instead of waiting for the whole reply to finish generating.

    If the service is unreachable or errors before yielding anything, yields
    one safe fallback message instead - a call in progress shouldn't die
    just because one downstream service hiccuped.
    """
    yielded_anything = False
    try:
        async with http_client.stream(
            "POST",
            NLU_SERVICE_URL,
            json={"token": NLU_SERVICE_TOKEN, "conversation_history": conversation_history},
        ) as response:
            response.raise_for_status()
            async for line in response.aiter_lines():
                if not line:
                    continue
                data = json.loads(line)
                if "delta" in data:
                    yielded_anything = True
                    yield data["delta"]
                elif "error" in data:
                    logger.error("NLU Service reported an error mid-stream: %s", data["error"])
                    break
    except Exception as e:
        logger.exception("NLU Service call failed: %s", e)

    if not yielded_anything:
        yield "Sorry, I'm having trouble understanding right now. Could you say that again?"


@app.get("/health")
async def health():
    return {"status": "ok"}


@app.websocket("/ws/call")
async def handle_call(
    client_ws: WebSocket,
    token: str | None = None,
    encoding: str = "linear16",
    sample_rate: int = 16000,
):
    conn_id = uuid.uuid4().hex[:8]

    if ORCHESTRATOR_TOKEN and token != ORCHESTRATOR_TOKEN:
        logger.warning("[%s] rejected: missing or invalid token", conn_id)
        await client_ws.close(code=4401)
        return

    await client_ws.accept()
    session = CallSession(conn_id)
    logger.info("[%s] call started", conn_id)

    stt_url = f"{STT_SERVICE_URL}?token={STT_SERVICE_TOKEN}&encoding={encoding}&sample_rate={sample_rate}"
    tts_url = f"{TTS_SERVICE_URL}?token={TTS_SERVICE_TOKEN}"

    try:
        async with websockets.connect(stt_url) as stt_ws, websockets.connect(tts_url) as tts_ws:

            # TTS Service announces its audio format once, right on connect -
            # forward it so the caller's client knows how to play back the
            # raw PCM bytes that will follow.
            format_message = json.loads(await tts_ws.recv())
            await client_ws.send_text(json.dumps({
                "event": "audio_format",
                "sample_rate": format_message["sample_rate"],
                "sample_width": format_message["sample_width"],
                "channels": format_message["channels"],
            }))

            # --- Greeting ---
            await session.transition(CallState.GREETING)
            greeting_text = "Hello! How can I help you today?"
            await client_ws.send_text(json.dumps({"event": "bot_speech", "text": greeting_text}))
            await speak_text(tts_ws, client_ws, greeting_text)

            await session.transition(CallState.LISTENING)

            async def pump_audio_caller_to_stt():
                """Forwards the caller's audio to the STT Service."""
                try:
                    while True:
                        chunk = await client_ws.receive_bytes()
                        await stt_ws.send(chunk)
                except WebSocketDisconnect:
                    await stt_ws.close()

            async def pump_stt_events_to_orchestrator():
                """Reads transcript events from the STT Service and drives the state machine."""
                try:
                    async for message in stt_ws:
                        data = json.loads(message)

                        if data.get("event") == "speech_started":
                            # Caller started talking — this is the barge-in signal.
                            # Once TTS exists: if session.state == RESPONDING, stop
                            # playback here. For now, just forward it along.
                            await client_ws.send_text(json.dumps({"event": "caller_speaking"}))
                            continue

                        transcript = data.get("transcript")
                        if not transcript or not data.get("speech_final"):
                            continue  # only act once the caller has finished a full thought

                        await session.transition(CallState.THINKING)
                        logger.info("[%s] caller said: %s", conn_id, transcript)

                        session.conversation_history.append({"role": "user", "content": transcript})

                        await session.transition(CallState.RESPONDING)
                        full_reply = ""
                        chunker = SentenceChunker()
                        async for delta in stream_nlu_reply(session.conversation_history):
                            full_reply += delta
                            await client_ws.send_text(json.dumps({
                                "event": "bot_speech_chunk",
                                "text": delta,
                            }))
                            for sentence in chunker.add(delta):
                                await speak_text(tts_ws, client_ws, sentence)

                        remainder = chunker.flush()
                        if remainder:
                            await speak_text(tts_ws, client_ws, remainder)

                        await client_ws.send_text(json.dumps({"event": "bot_speech_end"}))

                        session.conversation_history.append({"role": "assistant", "content": full_reply})
                        await session.transition(CallState.LISTENING)
                except ConnectionClosed:
                    # Expected once the caller disconnects and we close the
                    # STT Service connection in response — not a real error,
                    # just the natural end of this call.
                    logger.info("[%s] STT Service connection closed", conn_id)

            await asyncio.gather(
                pump_audio_caller_to_stt(),
                pump_stt_events_to_orchestrator(),
            )

    except WebSocketDisconnect:
        logger.info("[%s] caller disconnected", conn_id)
    except Exception as e:
        logger.exception("[%s] error: %s", conn_id, e)
        try:
            await client_ws.send_text(json.dumps({"error": "orchestrator_failed", "detail": str(e)}))
        except Exception:
            pass
        await client_ws.close(code=1011)
    finally:
        await session.transition(CallState.CLOSED)
        logger.info("[%s] call ended", conn_id)