"""
Orchestrator — the conversation state machine.

  Caller  <---WebSocket--->  Orchestrator  <---WebSocket--->  STT Service
                                    |
                                    +---WebSocket---> NLU/LLM Service (HTTP)
                                    +---WebSocket---> TTS Service

- Caller connects to  ws://<host>:8001/ws/call?token=...
- Caller sends raw audio bytes (same format the STT Service expects)
- Orchestrator forwards that audio to the STT Service (as a client of it —
  same role your test_mic_stream.py script has been playing)
- On each transcript event, the Orchestrator advances its call state machine,
  calls the NLU/LLM Service for a real reply, and streams that reply through
  the sentence chunker into the TTS Service - so the caller hears the first
  sentence while later ones are still being generated by the LLM.
- Barge-in: response generation (NLU + TTS) runs as a separate cancellable
  task from STT event reading, specifically so that if the caller starts
  talking while the bot is responding, the Orchestrator notices immediately
  (rather than being stuck awaiting the response) and can cancel it, stop
  the caller's audio playback, and reconnect to TTS to guarantee no stale
  audio from the interrupted reply leaks into the next one.

Run with:
    uvicorn orchestrator_service:app --reload --port 8001

Needs the STT, NLU, and TTS Services already running (ports 8000/8002/8003).
"""

import asyncio
import json
import logging
import os
import uuid
from contextlib import asynccontextmanager

import httpx
import websockets
from dotenv import load_dotenv
from fastapi import FastAPI, WebSocket, WebSocketDisconnect
from websockets.exceptions import ConnectionClosed

from call_state import CallSession, CallState
from flow_engine import FlowRun, FlowStage, flow_menu, pick_flow
from sentence_chunker import SentenceChunker

load_dotenv()
logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
logger = logging.getLogger("orchestrator")

# One shared HTTP client for the whole process, instead of opening a new
# connection on every single turn. On localhost this saves relatively
# little, but it's the correct pattern regardless of where the NLU Service
# ends up running later, and costs nothing to do now.
http_client: httpx.AsyncClient | None = None


@asynccontextmanager
async def lifespan(app: FastAPI):
    global http_client
    http_client = httpx.AsyncClient(timeout=30.0)
    yield
    await http_client.aclose()


app = FastAPI(title="Orchestrator", lifespan=lifespan)

STT_SERVICE_URL = os.environ.get("STT_SERVICE_URL", "ws://localhost:8000/ws/transcribe")
STT_SERVICE_TOKEN = os.environ.get("STT_SERVICE_TOKEN", "")

NLU_SERVICE_URL = os.environ.get("NLU_SERVICE_URL", "http://localhost:8002/reply/stream")
NLU_SERVICE_TOKEN = os.environ.get("NLU_SERVICE_TOKEN", "")

TTS_SERVICE_URL = os.environ.get("TTS_SERVICE_URL", "ws://localhost:8003/ws/synthesize")
TTS_SERVICE_TOKEN = os.environ.get("TTS_SERVICE_TOKEN", "")

# How long to wait, after an interruption, before assuming the caller wasn't
# actually about to say something and resuming the interrupted reply instead.
RESUME_TIMEOUT_SECONDS = float(os.environ.get("RESUME_TIMEOUT_SECONDS", "1.5"))

# Whether STT's speech_started should also trigger barge-in. Off by default:
# the client's local VAD detects speech faster (no network round trip) and,
# in testing, far more reliably - STT fired dozens of spurious speech_started
# events per call. Turn on only if local VAD is missing genuine speech.
STT_BARGE_IN_ENABLED = os.environ.get("STT_BARGE_IN", "false").lower() == "true"

TENANT_SERVICE_URL = os.environ.get("TENANT_SERVICE_URL", "http://localhost:8004")
TENANT_SERVICE_TOKEN = os.environ.get("TENANT_SERVICE_TOKEN", "")

DEFAULT_GREETING = "Hello! How can I help you today?"


async def load_tenant(tenant_id: str | None) -> dict | None:
    """
    Fetches a tenant's config at call start. Returns None if no tenant was
    specified, the tenant doesn't exist, or the service is unreachable - in
    which case the Orchestrator falls back to generic defaults rather than
    refusing the call. A config lookup failure shouldn't mean a customer
    can't reach anyone.
    """
    if not tenant_id:
        return None
    try:
        response = await http_client.get(
            f"{TENANT_SERVICE_URL}/tenants/{tenant_id}",
            params={"token": TENANT_SERVICE_TOKEN},
        )
        if response.status_code == 404:
            logger.warning("Unknown tenant_id %r - using defaults", tenant_id)
            return None
        response.raise_for_status()
        return response.json()
    except Exception as e:
        logger.exception("Failed to load tenant %r: %s", tenant_id, e)
        return None


async def load_flows(tenant_id: str | None) -> list[dict]:
    """
    Fetches a tenant's active flows at call start. Failure returns an empty
    list rather than raising - the bot degrades to plain conversation
    instead of the call failing outright.
    """
    if not tenant_id:
        return []
    try:
        response = await http_client.get(
            f"{TENANT_SERVICE_URL}/tenants/{tenant_id}/flows",
            params={"token": TENANT_SERVICE_TOKEN},
        )
        response.raise_for_status()
        return response.json().get("flows", [])
    except Exception as e:
        logger.exception("Failed to load flows for %r: %s", tenant_id, e)
        return []

ORCHESTRATOR_TOKEN = os.environ.get("ORCHESTRATOR_TOKEN")
if not ORCHESTRATOR_TOKEN:
    logger.warning(
        "ORCHESTRATOR_TOKEN is not set — /ws/call is UNAUTHENTICATED. "
        "Fine for local testing, not for anything public."
    )


class PlaybackClock:
    """
    Tracks when the audio we've sent will actually finish playing.

    Why this exists: the enclosing response task must stay alive as long as
    the caller is still HEARING the reply, otherwise barge-in has nothing to
    cancel (see handle_call). But sleeping after each individual sentence -
    the obvious way to do that - blocks the next sentence's synthesis until
    the previous one finishes playing, which inserts an audible gap of
    silence between every sentence while TTS works.

    Instead we track a running deadline: each sentence's audio pushes the
    deadline out by its own duration, and we only actually sleep once at the
    end. Synthesis for sentence 2 therefore happens WHILE sentence 1 is
    still playing on the client (whose queue preserves ordering), so the
    audio comes out continuous.
    """

    def __init__(self, audio_format: dict):
        self._bytes_per_second = (
            audio_format["sample_rate"] * audio_format["sample_width"] * audio_format["channels"]
        )
        self._deadline: float | None = None

    def add_audio(self, num_bytes: int):
        if self._bytes_per_second <= 0 or num_bytes <= 0:
            return
        duration = num_bytes / self._bytes_per_second
        now = asyncio.get_event_loop().time()
        # If previous audio has already finished playing, this starts now;
        # otherwise it queues behind what's still playing.
        start_from = max(now, self._deadline) if self._deadline is not None else now
        self._deadline = start_from + duration

    async def wait_until_finished(self):
        if self._deadline is None:
            return
        remaining = self._deadline - asyncio.get_event_loop().time()
        if remaining > 0:
            await asyncio.sleep(remaining)


async def speak_text(tts_ws, client_ws, text: str, clock: "PlaybackClock"):
    """
    Sends one complete sentence to the (already open, persistent) TTS
    Service connection and relays the resulting audio straight to the
    caller as it's generated. This is what actually lets the bot start
    speaking sentence 1 while the LLM is still generating sentence 2.

    Returns as soon as the audio has been relayed - it does NOT wait for
    playback. The caller records the duration on the shared PlaybackClock
    and waits once at the end instead, so synthesis of the next sentence
    overlaps with playback of this one.

    Failures here are logged and swallowed, not raised - losing the audio
    for one sentence shouldn't end the whole call.
    """
    if tts_ws is None:
        logger.error("No TTS connection available - skipping audio for this sentence.")
        return

    try:
        await tts_ws.send(text)
        bytes_sent = 0
        while True:
            message = await tts_ws.recv()
            if isinstance(message, bytes):
                await client_ws.send_bytes(message)
                bytes_sent += len(message)
            else:
                data = json.loads(message)
                if data.get("event") == "utterance_end":
                    break
                if "error" in data:
                    logger.error("TTS Service reported an error: %s", data.get("detail"))
                    break

        clock.add_audio(bytes_sent)
    except Exception as e:
        logger.exception("TTS Service call failed: %s", e)


async def stream_nlu_reply(
    conversation_history: list[dict],
    tenant: dict | None = None,
    flow_instructions: str | None = None,
    extract_fields: list[dict] | None = None,
):
    """
    Calls the NLU/LLM Service's streaming endpoint and yields text deltas as
    they arrive - this is what lets the Orchestrator react to the first few
    words instead of waiting for the whole reply to finish generating.

    The tenant's system_prompt_extra (and other context like business name
    and capabilities) is passed along so the LLM knows which business it's
    answering for. The NLU service stays stateless - it doesn't look
    tenants up itself, it just uses whatever context it's given.

    If the service is unreachable or errors before yielding anything, yields
    one safe fallback message instead - a call in progress shouldn't die
    just because one downstream service hiccuped.
    """
    payload = {"token": NLU_SERVICE_TOKEN, "conversation_history": conversation_history}
    if flow_instructions:
        payload["flow_instructions"] = flow_instructions
    if extract_fields:
        payload["extract_fields"] = extract_fields
    if tenant:
        payload["tenant_context"] = {
            "business_name": tenant.get("business_name"),
            "system_prompt_extra": tenant.get("system_prompt_extra", ""),
            "capabilities": tenant.get("capabilities", []),
            "business_hours": tenant.get("business_hours"),
            "escalation_phone": tenant.get("escalation_phone"),
        }

    yielded_anything = False
    try:
        async with http_client.stream(
            "POST",
            NLU_SERVICE_URL,
            json=payload,
        ) as response:
            response.raise_for_status()
            async for line in response.aiter_lines():
                if not line:
                    continue
                data = json.loads(line)
                if "delta" in data:
                    yielded_anything = True
                    yield data
                elif "extracted" in data:
                    yield data
                elif "error" in data:
                    logger.error("NLU Service reported an error mid-stream: %s", data["error"])
                    break
    except Exception as e:
        logger.exception("NLU Service call failed: %s", e)

    if not yielded_anything:
        yield {"delta": "Sorry, I'm having trouble understanding right now. Could you say that again?"}


@app.get("/health")
async def health():
    return {"status": "ok"}


@app.websocket("/ws/call")
async def handle_call(
    client_ws: WebSocket,
    token: str | None = None,
    tenant_id: str | None = None,
    encoding: str = "linear16",
    sample_rate: int = 16000,
):
    conn_id = uuid.uuid4().hex[:8]

    if ORCHESTRATOR_TOKEN and token != ORCHESTRATOR_TOKEN:
        logger.warning("[%s] rejected: missing or invalid token", conn_id)
        await client_ws.close(code=4401)
        return

    await client_ws.accept()
    session = CallSession(conn_id)
    session.tenant = await load_tenant(tenant_id)
    session.flows = await load_flows(tenant_id)
    if session.flows:
        logger.info("[%s] loaded %d flow(s): %s", conn_id, len(session.flows),
                    ", ".join(f.get("flow_id", "?") for f in session.flows))
    if session.tenant:
        logger.info(
            "[%s] call started for tenant %s (%s)",
            conn_id, tenant_id, session.tenant.get("business_name"),
        )
    else:
        logger.info("[%s] call started (no tenant - using defaults)", conn_id)

    stt_url = f"{STT_SERVICE_URL}?token={STT_SERVICE_TOKEN}&encoding={encoding}&sample_rate={sample_rate}"
    tts_url = f"{TTS_SERVICE_URL}?token={TTS_SERVICE_TOKEN}"

    # Held in a mutable box (not a plain variable) so reconnect_tts() can
    # replace it and every other function here immediately sees the new
    # connection - Python closures capture the box by reference, but a bare
    # local variable reassigned via `nonlocal` gets fiddlier to share
    # cleanly across this many nested functions.
    tts_box = {"ws": None}

    async def _close_quietly(ws):
        try:
            await ws.close()
        except Exception:
            pass

    async def reconnect_tts():
        """
        Closes the current TTS connection (if any) and opens a fresh one.

        Why this exists: if we cancel a response mid-sentence, the TTS
        Service (and Piper's own background synthesis thread) has no idea
        we stopped listening - it keeps generating and will keep trying to
        send audio for the interrupted sentence over the OLD connection.
        Reconnecting guarantees those stale leftovers can never bleed into
        the next sentence's audio, instead of trying to carefully drain an
        unknown amount of in-flight data.

        Important: closing the OLD connection is fired off in the
        background rather than awaited. If Piper is still busy on that
        connection's abandoned synthesis job, a graceful close handshake
        can genuinely take seconds to complete (its background thread has
        no idea we've moved on) - and there's no reason to make the caller
        wait for that cleanup before we're ready to speak again.

        If the reconnect itself fails (TTS Service down, network hiccup,
        etc.) this is caught and logged rather than left to propagate - a
        TTS problem shouldn't be able to take down an otherwise-working
        call. Worst case, tts_box["ws"] ends up None and subsequent
        speak_text() calls fail gracefully too (they already catch
        everything), meaning the caller still gets text responses even if
        audio is temporarily unavailable.
        """
        old_ws = tts_box["ws"]
        if old_ws is not None:
            asyncio.create_task(_close_quietly(old_ws))
        try:
            new_ws = await websockets.connect(tts_url)
            await new_ws.recv()  # discard the format announcement - already known
            tts_box["ws"] = new_ws
        except Exception as e:
            logger.exception("[%s] failed to reconnect to TTS Service: %s", conn_id, e)
            tts_box["ws"] = None

    try:
        async with websockets.connect(stt_url) as stt_ws:
            tts_box["ws"] = await websockets.connect(tts_url)

            # TTS Service announces its audio format once, right on connect -
            # forward it so the caller's client knows how to play back the
            # raw PCM bytes that will follow.
            format_message = json.loads(await tts_box["ws"].recv())
            audio_format = {
                "sample_rate": format_message["sample_rate"],
                "sample_width": format_message["sample_width"],
                "channels": format_message["channels"],
            }
            await client_ws.send_text(json.dumps({"event": "audio_format", **audio_format}))

            current_response_task: asyncio.Task | None = None

            async def speak_greeting():
                await session.transition(CallState.GREETING)
                greeting_text = (
                    session.tenant.get("greeting", DEFAULT_GREETING)
                    if session.tenant else DEFAULT_GREETING
                )
                await client_ws.send_text(json.dumps({"event": "bot_speech", "text": greeting_text}))
                try:
                    clock = PlaybackClock(audio_format)
                    await speak_text(tts_box["ws"], client_ws, greeting_text, clock)
                    await clock.wait_until_finished()
                    await session.transition(CallState.LISTENING)
                except asyncio.CancelledError:
                    logger.info("[%s] greeting interrupted by caller", conn_id)
                    raise

            async def speak_reply_text(full_text_source):
                """
                Shared core: sentence-chunks whatever text comes out of
                full_text_source (either live NLU deltas or a fixed cached
                string) and speaks each complete sentence as it's ready.
                Returns the full text actually spoken. Used by both a fresh
                response and a resumed one, so they share identical
                chunking/speaking/cancellation behavior.

                Important: this is where full_reply is actually accumulated,
                so this is also where it must be saved if cancelled - a
                caller that only captures the RETURN VALUE of this function
                (e.g. `full_reply = await speak_reply_text(...)`) would
                never see any partial progress on cancellation, since a
                cancelled call never reaches its return statement at all.
                """
                full_reply = ""
                extracted_all: dict = {}
                chunker = SentenceChunker()
                clock = PlaybackClock(audio_format)
                try:
                    async for event in full_text_source:
                        if "extracted" in event:
                            extracted_all.update(event["extracted"])
                            continue
                        delta = event.get("delta", "")
                        if not delta:
                            continue
                        full_reply += delta
                        await client_ws.send_text(json.dumps({
                            "event": "bot_speech_chunk",
                            "text": delta,
                        }))
                        for sentence in chunker.add(delta):
                            await speak_text(tts_box["ws"], client_ws, sentence, clock)

                    remainder = chunker.flush()
                    if remainder:
                        await speak_text(tts_box["ws"], client_ws, remainder, clock)

                    # Stay alive until the caller has actually finished
                    # hearing everything, so barge-in still has something to
                    # cancel during playback.
                    await clock.wait_until_finished()

                    return full_reply, extracted_all
                except asyncio.CancelledError:
                    if full_reply.strip():
                        session.pending_resume_text = full_reply
                    raise

            async def respond_to(transcript: str):
                """
                The full 'answer this' pipeline: NLU streaming -> sentence
                chunking -> TTS -> audio to caller. Runs as its own task so
                the STT event loop stays free to detect barge-in while this
                is in progress.
                """
                session.conversation_history.append({"role": "user", "content": transcript})
                await session.transition(CallState.THINKING)
                logger.info("[%s] caller said: %s", conn_id, transcript)

                # --- Flow steering ---
                # If a flow is running, tell the LLM exactly what's still
                # needed and give it a tool to report what it heard. If none
                # is running, offer the menu so it can start one.
                flow_instructions = None
                extract_fields = None
                run = session.active_flow

                if run and run.stage == FlowStage.CONFIRMING:
                    # The caller is answering a yes/no confirmation. Decide
                    # from their words rather than asking the model again -
                    # this is cheap and avoids an extra round trip.
                    lowered = transcript.lower()
                    if any(w in lowered for w in ("yes", "yeah", "correct", "right", "confirm", "that's it")):
                        run.confirm(True)
                    elif any(w in lowered for w in ("no", "wrong", "not", "change", "actually")):
                        run.confirm(False)

                if run and run.stage != FlowStage.DONE:
                    flow_instructions = run.instructions()
                    extract_fields = run.extraction_fields()
                elif session.flows:
                    # No flow running. Offer the menu, and give the model a
                    # field to report which one the caller is asking for -
                    # reusing the same extraction mechanism rather than
                    # adding a second one.
                    flow_instructions = (
                        flow_menu(session.flows)
                        + "\n\nIf the caller is asking for one of these, record its id in "
                          "_start_flow. If they're just chatting or asking a question, leave it empty."
                    )
                    extract_fields = [{
                        "name": "_start_flow",
                        "prompt": "the id of the task the caller wants, if any",
                        "options": [f.get("flow_id") for f in session.flows if f.get("flow_id")],
                    }]

                await session.transition(CallState.RESPONDING)
                try:
                    full_reply, extracted = await speak_reply_text(
                        stream_nlu_reply(
                            session.conversation_history,
                            session.tenant,
                            flow_instructions,
                            extract_fields,
                        )
                    )
                except asyncio.CancelledError:
                    # Caller talked over the bot. speak_reply_text has
                    # already stashed whatever partial text existed into
                    # session.pending_resume_text if there was any - see
                    # maybe_resume_after_timeout for what happens with it.
                    logger.info("[%s] response interrupted by caller", conn_id)
                    raise

                await client_ws.send_text(json.dumps({"event": "bot_speech_end"}))
                session.conversation_history.append({"role": "assistant", "content": full_reply})

                # --- Start a flow if the caller asked for one ---
                if not session.active_flow and extracted.get("_start_flow"):
                    chosen = pick_flow(session.flows, extracted["_start_flow"])
                    if chosen:
                        session.active_flow = FlowRun(chosen)
                        session.active_flow.advance()
                        logger.info("[%s] started flow %s", conn_id, chosen.get("flow_id"))
                        # The caller may have given details in the same
                        # breath ("book me in, it's Omar") - don't waste them.
                        details = {k: v for k, v in extracted.items() if k != "_start_flow"}
                        if details:
                            session.active_flow.apply_values(details)
                            session.active_flow.advance()

                # --- Apply anything new the caller told us ---
                elif session.active_flow and extracted:
                    rejected = session.active_flow.apply_values(extracted)
                    if rejected:
                        logger.info("[%s] flow rejected values: %s", conn_id, rejected)

                # --- Recompute stage and act. Deliberately OUTSIDE the
                # "did we extract anything" branch: a confirmation turn
                # ("yes, that's right") carries no new field values, but is
                # exactly the turn that moves a flow to READY. Gating this
                # on extraction meant confirmed bookings never fired.
                if session.active_flow and session.active_flow.stage != FlowStage.DONE:
                    session.active_flow.advance()
                    logger.info("[%s] flow %s -> %s (have: %s)", conn_id,
                                session.active_flow.flow_id,
                                session.active_flow.stage.value,
                                list(session.active_flow.values))

                    if session.active_flow.stage == FlowStage.READY:
                        await run_flow_action(session.active_flow)

                await session.transition(CallState.LISTENING)

            async def run_flow_action(run):
                """
                Everything is collected and confirmed. The Connector Gateway
                doesn't exist yet, so this logs what WOULD be called and
                speaks the success line - the seam is here, ready for it.
                """
                action = run.flow.get("action")
                logger.info("[%s] FLOW COMPLETE %s | action=%s | values=%s",
                            conn_id, run.flow_id, action, run.values)

                message = run.flow.get("on_success") or "All done."
                for name, value in run.values.items():
                    message = message.replace("{" + name + "}", str(value))

                await client_ws.send_text(json.dumps({
                    "event": "flow_complete",
                    "flow_id": run.flow_id,
                    "values": run.values,
                    "action": action,
                }))

                clock = PlaybackClock(audio_format)
                await speak_text(tts_box["ws"], client_ws, message, clock)
                await clock.wait_until_finished()

                session.conversation_history.append({"role": "assistant", "content": message})
                run.stage = FlowStage.DONE
                session.active_flow = None

            async def resume_response(text: str):
                """
                Re-speaks previously-generated text that got cut off by an
                interruption, when the caller doesn't follow up with
                anything new. Skips the NLU call entirely - the text is
                already known, this is a replay, not a new turn.

                Worth knowing: this replays only the portion that had
                already been generated before the interruption, not a
                continuation of what the LLM would have said next - that
                part was never generated, since interrupting also cancels
                the NLU stream itself.
                """
                logger.info("[%s] no follow-up from caller - resuming interrupted reply", conn_id)
                await session.transition(CallState.RESPONDING)

                async def single_chunk_source():
                    yield text

                try:
                    full_reply, _ = await speak_reply_text(single_chunk_source())
                except asyncio.CancelledError:
                    logger.info("[%s] resumed response interrupted again", conn_id)
                    raise

                await client_ws.send_text(json.dumps({"event": "bot_speech_end"}))
                session.conversation_history.append({"role": "assistant", "content": full_reply})
                await session.transition(CallState.LISTENING)

            async def cancel_current_response() -> bool:
                """
                Cancels the in-progress response, if any, and cleans up
                after it. Returns True if something was actually cancelled
                (as opposed to there being nothing active to begin with) -
                callers use this to decide whether a resume attempt makes
                sense afterward.
                """
                nonlocal current_response_task
                cancelled_something = False
                if current_response_task is not None and not current_response_task.done():
                    cancelled_something = True
                    logger.info("[%s] cancelling in-progress response task", conn_id)
                    current_response_task.cancel()
                    try:
                        await current_response_task
                    except asyncio.CancelledError:
                        pass
                    await session.transition(CallState.LISTENING)
                    await reconnect_tts()
                else:
                    logger.info(
                        "[%s] cancel_current_response called - nothing to cancel (task=%s, done=%s)",
                        conn_id,
                        current_response_task is not None,
                        current_response_task.done() if current_response_task is not None else None,
                    )
                current_response_task = None
                return cancelled_something

            resume_timer_task: asyncio.Task | None = None

            async def cancel_resume_timer():
                """Cancels a pending resume attempt - called whenever the caller does ANYTHING new."""
                nonlocal resume_timer_task
                if resume_timer_task is not None and not resume_timer_task.done():
                    resume_timer_task.cancel()
                    try:
                        await resume_timer_task
                    except asyncio.CancelledError:
                        pass
                resume_timer_task = None

            async def maybe_resume_after_timeout():
                """
                Waits a short grace period after an interruption. If the
                caller hasn't said anything new by then, assumes they
                didn't actually mean to interrupt (false trigger, cleared
                throat, brief noise) and resumes the cut-off reply instead
                of just leaving it dropped.
                """
                nonlocal current_response_task
                await asyncio.sleep(RESUME_TIMEOUT_SECONDS)
                if session.pending_resume_text:
                    text_to_resume = session.pending_resume_text
                    session.pending_resume_text = None
                    current_response_task = asyncio.create_task(resume_response(text_to_resume))

            async def handle_barge_in(source: str):
                """
                Shared barge-in path, triggered by the client's local VAD
                (fast - detects speech in ~100ms without a network round
                trip) or optionally by the STT service's speech_started.

                Gated on the bot actually speaking: in practice both
                detectors fire constantly during normal conversation
                (every time the caller talks at all, including when
                answering a question the bot just asked). Acting on those
                is pointless work and floods the logs - there's nothing to
                interrupt when the bot isn't talking.
                """
                nonlocal resume_timer_task
                if session.state not in (CallState.RESPONDING, CallState.GREETING):
                    return

                logger.info("[%s] barge-in detected (source=%s)", conn_id, source)
                await client_ws.send_text(json.dumps({"event": "bot_interrupted"}))
                await cancel_resume_timer()
                cancelled = await cancel_current_response()
                if cancelled:
                    resume_timer_task = asyncio.create_task(maybe_resume_after_timeout())

            async def pump_audio_caller_to_stt():
                """
                Forwards the caller's audio to the STT Service, and handles
                control messages the client sends alongside it (currently
                just its local-VAD barge-in signal).
                """
                try:
                    while True:
                        message = await client_ws.receive()

                        if message.get("type") == "websocket.disconnect":
                            raise WebSocketDisconnect(message.get("code", 1000))

                        if "bytes" in message and message["bytes"] is not None:
                            try:
                                await stt_ws.send(message["bytes"])
                            except ConnectionClosed:
                                # STT service dropped the connection. Losing
                                # transcription is bad, but it shouldn't take
                                # the whole call down - the caller can still
                                # hear the bot, and local VAD still works.
                                logger.error(
                                    "[%s] STT connection lost - transcription stopped, call continues",
                                    conn_id,
                                )
                                return
                            continue

                        if "text" in message and message["text"] is not None:
                            data = json.loads(message["text"])
                            if data.get("event") == "client_speech_start":
                                await handle_barge_in("client_vad")
                except WebSocketDisconnect:
                    try:
                        await stt_ws.close()
                    except Exception:
                        pass

            async def pump_stt_events_to_orchestrator():
                """Reads transcript events from the STT Service and drives the state machine."""
                nonlocal current_response_task
                nonlocal resume_timer_task
                try:
                    async for message in stt_ws:
                        data = json.loads(message)

                        if data.get("event") == "speech_started":
                            await client_ws.send_text(json.dumps({"event": "caller_speaking"}))
                            # STT's speech detection travels a full network
                            # round trip (mic -> STT service -> Deepgram ->
                            # back), so it's always later than the client's
                            # local VAD, and in practice much noisier. Local
                            # VAD owns interruption; STT owns transcription.
                            # Set STT_BARGE_IN=true to re-enable it as a
                            # backstop if local VAD is missing real speech.
                            if STT_BARGE_IN_ENABLED:
                                await handle_barge_in("stt")
                            continue

                        transcript = data.get("transcript")
                        if not transcript or not data.get("speech_final"):
                            continue  # only act once the caller has finished a full thought

                        # A real new question - any pending resume is now
                        # moot, the caller has moved on.
                        await cancel_resume_timer()
                        session.pending_resume_text = None

                        # Safety net: speech_started should already have
                        # cancelled anything in-flight by the time a final
                        # transcript arrives, but if timing ever slips,
                        # never let two responses run concurrently.
                        await cancel_current_response()

                        current_response_task = asyncio.create_task(respond_to(transcript))
                except ConnectionClosed:
                    # Expected once the caller disconnects and we close the
                    # STT Service connection in response — not a real error,
                    # just the natural end of this call.
                    logger.info("[%s] STT Service connection closed", conn_id)

            # Start the greeting as the FIRST cancellable response task, at
            # the same time as audio forwarding begins - not before it. If
            # the greeting blocked here before the pumps below started
            # running, caller audio arriving during that window would just
            # sit unread on the server until the pumps finally started,
            # then get forwarded to STT all at once in a compressed burst -
            # which STT would misread as several rapid, confused speech
            # onsets instead of one real one. Starting everything together
            # means the caller can barge in on the greeting itself too.
            current_response_task = asyncio.create_task(speak_greeting())

            await asyncio.gather(
                pump_audio_caller_to_stt(),
                pump_stt_events_to_orchestrator(),
            )

    except WebSocketDisconnect:
        logger.info("[%s] caller disconnected", conn_id)
    except Exception as e:
        logger.exception("[%s] error: %s", conn_id, e)
        try:
            await client_ws.send_text(json.dumps({"error": "orchestrator_failed", "detail": str(e)}))
        except Exception:
            pass
        await client_ws.close(code=1011)
    finally:
        if tts_box["ws"] is not None:
            try:
                await tts_box["ws"].close()
            except Exception:
                pass
        await session.transition(CallState.CLOSED)
        logger.info("[%s] call ended", conn_id)
