"""
Orchestrator — the conversation state machine.

  Caller  <---WebSocket--->  Orchestrator  <---WebSocket--->  STT Service
                                    |
                                    +---WebSocket---> NLU/LLM Service (HTTP)
                                    +---WebSocket---> TTS Service

- Caller connects to  ws://<host>:8001/ws/call?token=...
- Caller sends raw audio bytes (same format the STT Service expects)
- Orchestrator forwards that audio to the STT Service (as a client of it —
  same role your test_mic_stream.py script has been playing)
- On each transcript event, the Orchestrator advances its call state machine,
  calls the NLU/LLM Service for a real reply, and streams that reply through
  the sentence chunker into the TTS Service - so the caller hears the first
  sentence while later ones are still being generated by the LLM.
- Barge-in: response generation (NLU + TTS) runs as a separate cancellable
  task from STT event reading, specifically so that if the caller starts
  talking while the bot is responding, the Orchestrator notices immediately
  (rather than being stuck awaiting the response) and can cancel it, stop
  the caller's audio playback, and reconnect to TTS to guarantee no stale
  audio from the interrupted reply leaks into the next one.

Run with:
    uvicorn orchestrator_service:app --reload --port 8001

Needs the STT, NLU, and TTS Services already running (ports 8000/8002/8003).
"""

import asyncio
import json
import logging
import os
import uuid
from contextlib import asynccontextmanager

import httpx
import websockets
from dotenv import load_dotenv
from fastapi import FastAPI, WebSocket, WebSocketDisconnect
from websockets.exceptions import ConnectionClosed

from call_state import CallSession, CallState
from sentence_chunker import SentenceChunker

load_dotenv()
logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
logger = logging.getLogger("orchestrator")

# One shared HTTP client for the whole process, instead of opening a new
# connection on every single turn. On localhost this saves relatively
# little, but it's the correct pattern regardless of where the NLU Service
# ends up running later, and costs nothing to do now.
http_client: httpx.AsyncClient | None = None


@asynccontextmanager
async def lifespan(app: FastAPI):
    global http_client
    http_client = httpx.AsyncClient(timeout=30.0)
    yield
    await http_client.aclose()


app = FastAPI(title="Orchestrator", lifespan=lifespan)

STT_SERVICE_URL = os.environ.get("STT_SERVICE_URL", "ws://localhost:8000/ws/transcribe")
STT_SERVICE_TOKEN = os.environ.get("STT_SERVICE_TOKEN", "")

NLU_SERVICE_URL = os.environ.get("NLU_SERVICE_URL", "http://localhost:8002/reply/stream")
NLU_SERVICE_TOKEN = os.environ.get("NLU_SERVICE_TOKEN", "")

TTS_SERVICE_URL = os.environ.get("TTS_SERVICE_URL", "ws://localhost:8003/ws/synthesize")
TTS_SERVICE_TOKEN = os.environ.get("TTS_SERVICE_TOKEN", "")

ORCHESTRATOR_TOKEN = os.environ.get("ORCHESTRATOR_TOKEN")
if not ORCHESTRATOR_TOKEN:
    logger.warning(
        "ORCHESTRATOR_TOKEN is not set — /ws/call is UNAUTHENTICATED. "
        "Fine for local testing, not for anything public."
    )


async def speak_text(tts_ws, client_ws, text: str, audio_format: dict):
    """
    Sends one complete sentence to the (already open, persistent) TTS
    Service connection and relays the resulting audio straight to the
    caller as it's generated. This is what actually lets the bot start
    speaking sentence 1 while the LLM is still generating sentence 2.

    Important: after relaying all the audio bytes, this waits for roughly
    how long that audio actually takes to play back before returning.
    Without this, relaying bytes over localhost is basically instant, so
    the enclosing response task would be marked "done" long before the
    caller has actually finished HEARING the reply - meaning a barge-in
    attempt while audio is still audibly playing would find nothing left
    to cancel. This keeps the task's lifetime honest against real playback
    time, which is exactly what the cancellation check in handle_call
    depends on. It costs nothing in perceived latency - the caller was
    always going to spend this long listening anyway.

    Failures here are logged and swallowed, not raised - losing the audio
    for one sentence shouldn't end the whole call.
    """
    if tts_ws is None:
        logger.error("No TTS connection available - skipping audio for this sentence.")
        return

    try:
        await tts_ws.send(text)
        bytes_sent = 0
        while True:
            message = await tts_ws.recv()
            if isinstance(message, bytes):
                await client_ws.send_bytes(message)
                bytes_sent += len(message)
            else:
                data = json.loads(message)
                if data.get("event") == "utterance_end":
                    break
                if "error" in data:
                    logger.error("TTS Service reported an error: %s", data.get("detail"))
                    break

        bytes_per_second = (
            audio_format["sample_rate"] * audio_format["sample_width"] * audio_format["channels"]
        )
        if bytes_per_second > 0 and bytes_sent > 0:
            await asyncio.sleep(bytes_sent / bytes_per_second)
    except Exception as e:
        logger.exception("TTS Service call failed: %s", e)


async def stream_nlu_reply(conversation_history: list[dict]):
    """
    Calls the NLU/LLM Service's streaming endpoint and yields text deltas as
    they arrive - this is what lets the Orchestrator react to the first few
    words instead of waiting for the whole reply to finish generating.

    If the service is unreachable or errors before yielding anything, yields
    one safe fallback message instead - a call in progress shouldn't die
    just because one downstream service hiccuped.
    """
    yielded_anything = False
    try:
        async with http_client.stream(
            "POST",
            NLU_SERVICE_URL,
            json={"token": NLU_SERVICE_TOKEN, "conversation_history": conversation_history},
        ) as response:
            response.raise_for_status()
            async for line in response.aiter_lines():
                if not line:
                    continue
                data = json.loads(line)
                if "delta" in data:
                    yielded_anything = True
                    yield data["delta"]
                elif "error" in data:
                    logger.error("NLU Service reported an error mid-stream: %s", data["error"])
                    break
    except Exception as e:
        logger.exception("NLU Service call failed: %s", e)

    if not yielded_anything:
        yield "Sorry, I'm having trouble understanding right now. Could you say that again?"


@app.get("/health")
async def health():
    return {"status": "ok"}


@app.websocket("/ws/call")
async def handle_call(
    client_ws: WebSocket,
    token: str | None = None,
    encoding: str = "linear16",
    sample_rate: int = 16000,
):
    conn_id = uuid.uuid4().hex[:8]

    if ORCHESTRATOR_TOKEN and token != ORCHESTRATOR_TOKEN:
        logger.warning("[%s] rejected: missing or invalid token", conn_id)
        await client_ws.close(code=4401)
        return

    await client_ws.accept()
    session = CallSession(conn_id)
    logger.info("[%s] call started", conn_id)

    stt_url = f"{STT_SERVICE_URL}?token={STT_SERVICE_TOKEN}&encoding={encoding}&sample_rate={sample_rate}"
    tts_url = f"{TTS_SERVICE_URL}?token={TTS_SERVICE_TOKEN}"

    # Held in a mutable box (not a plain variable) so reconnect_tts() can
    # replace it and every other function here immediately sees the new
    # connection - Python closures capture the box by reference, but a bare
    # local variable reassigned via `nonlocal` gets fiddlier to share
    # cleanly across this many nested functions.
    tts_box = {"ws": None}

    async def _close_quietly(ws):
        try:
            await ws.close()
        except Exception:
            pass

    async def reconnect_tts():
        """
        Closes the current TTS connection (if any) and opens a fresh one.

        Why this exists: if we cancel a response mid-sentence, the TTS
        Service (and Piper's own background synthesis thread) has no idea
        we stopped listening - it keeps generating and will keep trying to
        send audio for the interrupted sentence over the OLD connection.
        Reconnecting guarantees those stale leftovers can never bleed into
        the next sentence's audio, instead of trying to carefully drain an
        unknown amount of in-flight data.

        Important: closing the OLD connection is fired off in the
        background rather than awaited. If Piper is still busy on that
        connection's abandoned synthesis job, a graceful close handshake
        can genuinely take seconds to complete (its background thread has
        no idea we've moved on) - and there's no reason to make the caller
        wait for that cleanup before we're ready to speak again.

        If the reconnect itself fails (TTS Service down, network hiccup,
        etc.) this is caught and logged rather than left to propagate - a
        TTS problem shouldn't be able to take down an otherwise-working
        call. Worst case, tts_box["ws"] ends up None and subsequent
        speak_text() calls fail gracefully too (they already catch
        everything), meaning the caller still gets text responses even if
        audio is temporarily unavailable.
        """
        old_ws = tts_box["ws"]
        if old_ws is not None:
            asyncio.create_task(_close_quietly(old_ws))
        try:
            new_ws = await websockets.connect(tts_url)
            await new_ws.recv()  # discard the format announcement - already known
            tts_box["ws"] = new_ws
        except Exception as e:
            logger.exception("[%s] failed to reconnect to TTS Service: %s", conn_id, e)
            tts_box["ws"] = None

    try:
        async with websockets.connect(stt_url) as stt_ws:
            tts_box["ws"] = await websockets.connect(tts_url)

            # TTS Service announces its audio format once, right on connect -
            # forward it so the caller's client knows how to play back the
            # raw PCM bytes that will follow.
            format_message = json.loads(await tts_box["ws"].recv())
            audio_format = {
                "sample_rate": format_message["sample_rate"],
                "sample_width": format_message["sample_width"],
                "channels": format_message["channels"],
            }
            await client_ws.send_text(json.dumps({"event": "audio_format", **audio_format}))

            current_response_task: asyncio.Task | None = None

            async def speak_greeting():
                await session.transition(CallState.GREETING)
                greeting_text = "Hello! How can I help you today?"
                await client_ws.send_text(json.dumps({"event": "bot_speech", "text": greeting_text}))
                try:
                    await speak_text(tts_box["ws"], client_ws, greeting_text, audio_format)
                    await session.transition(CallState.LISTENING)
                except asyncio.CancelledError:
                    logger.info("[%s] greeting interrupted by caller", conn_id)
                    raise

            async def respond_to(transcript: str):
                """
                The full 'answer this' pipeline: NLU streaming -> sentence
                chunking -> TTS -> audio to caller. Runs as its own task so
                the STT event loop stays free to detect barge-in while this
                is in progress.
                """
                session.conversation_history.append({"role": "user", "content": transcript})
                await session.transition(CallState.THINKING)
                logger.info("[%s] caller said: %s", conn_id, transcript)

                await session.transition(CallState.RESPONDING)
                full_reply = ""
                chunker = SentenceChunker()
                try:
                    async for delta in stream_nlu_reply(session.conversation_history):
                        full_reply += delta
                        await client_ws.send_text(json.dumps({
                            "event": "bot_speech_chunk",
                            "text": delta,
                        }))
                        for sentence in chunker.add(delta):
                            await speak_text(tts_box["ws"], client_ws, sentence, audio_format)

                    remainder = chunker.flush()
                    if remainder:
                        await speak_text(tts_box["ws"], client_ws, remainder, audio_format)

                    await client_ws.send_text(json.dumps({"event": "bot_speech_end"}))
                    session.conversation_history.append({"role": "assistant", "content": full_reply})
                    await session.transition(CallState.LISTENING)
                except asyncio.CancelledError:
                    # Caller talked over the bot. Don't record the partial
                    # reply - it was never actually delivered, so it has no
                    # place in the conversation history. The barge-in
                    # handler below owns notifying the client and moving
                    # the state machine back to LISTENING.
                    logger.info("[%s] response interrupted by caller", conn_id)
                    raise

            async def cancel_current_response():
                """Cancels the in-progress response, if any, and cleans up after it."""
                nonlocal current_response_task
                if current_response_task is not None and not current_response_task.done():
                    logger.info("[%s] cancelling in-progress response task", conn_id)
                    current_response_task.cancel()
                    try:
                        await current_response_task
                    except asyncio.CancelledError:
                        pass
                    # Tell the client to stop audio playback FIRST, before
                    # anything else. Reconnecting TTS is purely internal
                    # bookkeeping for the NEXT response's audio integrity -
                    # it has nothing to do with stopping what's playing
                    # right now, and the caller shouldn't have to wait for
                    # it before the interruption actually takes effect.
                    await client_ws.send_text(json.dumps({"event": "bot_interrupted"}))
                    await session.transition(CallState.LISTENING)
                    await reconnect_tts()
                else:
                    logger.info(
                        "[%s] cancel_current_response called - nothing to cancel (task=%s, done=%s)",
                        conn_id,
                        current_response_task is not None,
                        current_response_task.done() if current_response_task is not None else None,
                    )
                current_response_task = None

            async def pump_audio_caller_to_stt():
                """Forwards the caller's audio to the STT Service."""
                try:
                    while True:
                        chunk = await client_ws.receive_bytes()
                        await stt_ws.send(chunk)
                except WebSocketDisconnect:
                    await stt_ws.close()

            async def pump_stt_events_to_orchestrator():
                """Reads transcript events from the STT Service and drives the state machine."""
                nonlocal current_response_task
                try:
                    async for message in stt_ws:
                        data = json.loads(message)

                        if data.get("event") == "speech_started":
                            logger.info("[%s] speech_started received from STT", conn_id)
                            # Caller started talking. If the bot is mid-response,
                            # this is a real barge-in - stop everything now.
                            await client_ws.send_text(json.dumps({"event": "caller_speaking"}))
                            await cancel_current_response()
                            continue

                        transcript = data.get("transcript")
                        if not transcript or not data.get("speech_final"):
                            continue  # only act once the caller has finished a full thought

                        # Safety net: speech_started should already have
                        # cancelled anything in-flight by the time a final
                        # transcript arrives, but if timing ever slips,
                        # never let two responses run concurrently.
                        await cancel_current_response()

                        current_response_task = asyncio.create_task(respond_to(transcript))
                except ConnectionClosed:
                    # Expected once the caller disconnects and we close the
                    # STT Service connection in response — not a real error,
                    # just the natural end of this call.
                    logger.info("[%s] STT Service connection closed", conn_id)

            # Start the greeting as the FIRST cancellable response task, at
            # the same time as audio forwarding begins - not before it. If
            # the greeting blocked here before the pumps below started
            # running, caller audio arriving during that window would just
            # sit unread on the server until the pumps finally started,
            # then get forwarded to STT all at once in a compressed burst -
            # which STT would misread as several rapid, confused speech
            # onsets instead of one real one. Starting everything together
            # means the caller can barge in on the greeting itself too.
            current_response_task = asyncio.create_task(speak_greeting())

            await asyncio.gather(
                pump_audio_caller_to_stt(),
                pump_stt_events_to_orchestrator(),
            )

    except WebSocketDisconnect:
        logger.info("[%s] caller disconnected", conn_id)
    except Exception as e:
        logger.exception("[%s] error: %s", conn_id, e)
        try:
            await client_ws.send_text(json.dumps({"error": "orchestrator_failed", "detail": str(e)}))
        except Exception:
            pass
        await client_ws.close(code=1011)
    finally:
        if tts_box["ws"] is not None:
            try:
                await tts_box["ws"].close()
            except Exception:
                pass
        await session.transition(CallState.CLOSED)
        logger.info("[%s] call ended", conn_id)